Use script to generate secret vars for terraform
Enables e.g. prod env. to control test and stage resources

Signed-off-by: Chris Evich <chris-cloud.icuc.me>

diff --git a/terraform/Makefile b/terraform/Makefile
--- a/terraform/Makefile
+++ b/terraform/Makefile
@@ -1,4 +1,8 @@
 
+SRC_DIR=$(shell realpath "$$PWD/../")
+SECRETS_DIR=$(SRC_DIR)/secrets
+TERRAFORM_DIR=$(SRC_DIR)/terraform
+
 .PHONY: all
 all: apply
 
@@ -10,28 +14,26 @@ guard-%:
 		exit 1; \
 	fi;
 
-$(ENV_NAME)/%.auto.tfvars:
-	cd "$(ENV_NAME)" && \
-		ln -sf ../../secrets/$(ENV_NAME)-$*.auto.tfvars ./$*.auto.tfvars
+$(SECRETS_DIR)/$(ENV_NAME)-%.auto.tfvars: guard-SECRETS_DIR guard-ENV_NAME
+	$(MAKE) -C "$(SECRETS_DIR)" ENV_NAME=$(ENV_NAME)
+
+$(ENV_NAME)/%.auto.tfvars: $(SECRETS_DIR)/$(ENV_NAME)-%.auto.tfvars
+	ln -sf "$^" "$(TERRAFORM_DIR)/$@"
 
 .PHONY: prepare
-prepare: guard-ENV_NAME $(ENV_NAME)/backend.auto.tfvars
-	bin/prepare.sh $(ENV_NAME)/backend.auto.tfvars
+prepare: guard-ENV_NAME guard-SECRETS_DIR $(SECRETS_DIR)/$(ENV_NAME)-backend.auto.tfvars
+	$(SRC_DIR)/bin/prepare.sh "$(SECRETS_DIR)/$(ENV_NAME)-backend.auto.tfvars"
 
 .PHONY: init
-init: guard-ENV_NAME $(ENV_NAME)/.terraform
-$(ENV_NAME)/.terraform: guard-ENV_NAME $(ENV_NAME)/backend.auto.tfvars prepare
+init: guard-ENV_NAME $(ENV_NAME)/.terraform/terraform.tfstate
+$(ENV_NAME)/.terraform/terraform.tfstate: guard-ENV_NAME $(ENV_NAME)/backend.auto.tfvars prepare
 	@cd "$(ENV_NAME)" && \
 		TF_IN_AUTOMATION=1 terraform init -input=false \
 			-backend-config="backend.auto.tfvars" \
 			-force-copy -upgrade=true
 
-$(ENV_NAME)/runtime.auto.tfvars: guard-ENV_NAME guard-SRC_VERSION
-	@echo 'env_name = "$(ENV_NAME)"' > "$@"
-	@echo 'src_version = "$(SRC_VERSION)"' >> "$@"
-
 .PHONY: auto.tfvars
-auto.tfvars: $(ENV_NAME)/backend.auto.tfvars $(ENV_NAME)/uuid.auto.tfvars $(ENV_NAME)/provider.auto.tfvars $(ENV_NAME)/runtime.auto.tfvars
+auto.tfvars: guard-SECRETS_DIR guard-ENV_NAME $(ENV_NAME)/backend.auto.tfvars $(ENV_NAME)/runtime.auto.tfvars
 
 $(ENV_NAME)/plan: guard-ENV_NAME init auto.tfvars
 	@cd "$(ENV_NAME)" && \
@@ -42,15 +44,6 @@ apply: guard-ENV_NAME $(ENV_NAME)/plan auto.tfvars
 	@cd "$(ENV_NAME)" && \
 		TF_IN_AUTOMATION=1 terraform apply -input=false -auto-approve ./plan
 
-.PHONY: teardown
-teardown: guard-ENV_NAME $(ENV_NAME)/backend.auto.tfvars $(ENV_NAME)/uuid.auto.tfvars
-	@if [[ "$(ENV_NAME)" =~ "prod" ]]; then \
-		echo "Cowardly refusing to teardown prod state."; \
-	elif [[ -n "$(ENV_NAME)" ]]; then \
-		bin/teardown.sh $(ENV_NAME)/backend.auto.tfvars || \
-		echo "Tearing down backend for $(ENV_NAME) ($(shell cat $(ENV_NAME)/uuid.auto.tfvars)) failed, you will have to clean it up manually"; \
-	fi
-
 .PHONY: destroy
 destroy: guard-ENV_NAME auto.tfvars
 	@if [[ "$(ENV_NAME)" =~ "prod" ]]; then \
@@ -58,7 +51,19 @@ destroy: guard-ENV_NAME auto.tfvars
 	elif [[ -n "$(ENV_NAME)" ]]; then \
 		cd "$(ENV_NAME)" && \
 			( TF_IN_AUTOMATION=1 terraform destroy -input=false -auto-approve || \
-			  echo "Destroying $(ENV_NAME) resources failed, manual cleanup required"; ) \
+			  echo "Destroying $(ENV_NAME) resources failed, manual cleanup required"; \
+			  exit 3; ) \
+	fi
+
+.PHONY: teardown
+teardown: guard-ENV_NAME guard-SECRETS_DIR $(SECRETS_DIR)/$(ENV_NAME)-backend.auto.tfvars
+	@if [[ "$(ENV_NAME)" =~ "prod" ]]; then \
+		echo "Cowardly refusing to teardown prod state."; \
+		exit 1; \
+	elif [[ -n "$(ENV_NAME)" ]]; then \
+		$(SRC_DIR)/bin/teardown.sh "$(SECRETS_DIR)/$(ENV_NAME)-backend.auto.tfvars" || \
+		( echo "Tearing down backend for $(ENV_NAME) failed, you may have to clean it up manually"; \
+		exit 2; ) \
 	fi
 
 .PHONY: clean
@@ -66,5 +71,5 @@ clean:
 	# ALL environments
 	-rm -fv {test,stage,prod}/plan
 	-rm -fv {test,stage,prod}/*tfstate*
-	-rm -fv {test,stage,prod}/{backend,provider,uuid,runtime}.auto.tfvars
+	-rm -fv {test,stage,prod}/{backend,runtime}.auto.tfvars
 	-rm -rvf {test,stage,prod}/.terraform/*
